apiVersion: autoheal.io/v1
kind: AutoHealPolicy
metadata:
  name: example-autoheal-policy
spec:
  selector:
    app: my-spring-app
  port: 8080
  coolDownSeconds: 31 # Slight change to trigger reconciliation
  rules:
    - type: UnresponsiveActuator
      action: Restart
    - type: MemoryLeak
      threshold: "90%"
      action: RestartWithDump
